# Generated by Django 3.1.2 on 2020-12-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201212_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
